name: Lint, build and test

on:
  push:
    branches: [main, prod]
  pull_request:
    branches: [main, prod]

jobs:
    build:
        runs-on: ubuntu-latest
    
        steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-node@v3
          with:
            node-version: '20.x'
        - run: npm install -g yarn
        - run: yarn install --frozen-lockfile
        - run: yarn lint
        - run: yarn build
        - run: yarn test
    

    github-pr-release:
        needs: build
        permissions:
            contents: read
            pull-requests: write
        runs-on: ubuntu-latest
        steps:
        
        - uses: actions/checkout@v3
        - uses: actions/setup-node@v3
          with:
            node-version: '20.x'
        - name: Changed files
          id: changed-files
          uses: tj-actions/changed-files@v44
        - name: Exit on no mini-md/** changes
          env:
            files: ${{ steps.changed-files.outputs.all_changed_and_modified_files }}
          run: |
            for file in $files; do
              if [[ $file == "mini-md/"* ]]; then
                echo "Changes in mini-md/ detected"
                exit 0
              fi
            done
            echo "No changes in mini-md/ detected"
            exit 1
        - run: npm install -g yarn
        - run: yarn install --frozen-lockfile
        - run: yarn script:release-pr
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
