name: Lint, build and test

on:
  push:
    branches:
        - main
        - prod
  pull_request:
    branches:
        - main
        - prod

jobs:
    build:
        runs-on: ubuntu-latest
    
        steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-node@v3
          with:
            node-version: '20.x'
        - run: npm install -g yarn
        - run: yarn install --frozen-lockfile
        - run: yarn lint
        - run: yarn build
        - run: yarn test