name: Make Release Tag
on: 
  push:
    branches:
    - prod
    
jobs:
    release-on-push:
      permissions:
        contents: write
        pull-requests: read
      runs-on: ubuntu-latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      steps:
        - name: Create Release Tag
          id: rel
          uses: rymndhng/release-on-push-action@master
          with:
            bump_version_scheme: patch
      outputs:
        release_tag: ${{ steps.rel.outputs.tag_name }}
        
    publish:
        needs: release-on-push
        runs-on: ubuntu-latest
        permissions:
            contents: read
            id-token: write
        steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-node@v3
          with:
            node-version: '20.x'
            registry-url: 'https://registry.npmjs.org'
        - run: npm install -g yarn
        - run: yarn install --frozen-lockfile
        - name: Setup git user
          run: |
            git config --global user.name "$(git --no-pager log --format=format:'%an' -n 1)"
            git config --global user.email "$(git --no-pager log --format=format:'%ae' -n 1)"
        - name: Publish
          run: |
            version=${{ needs.release-on-push.outputs.release_tag }}
            echo "Publishing version $version"
            yarn workspace mini-md publish --provenance --new-version ${version/v/}
          env:
            NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
                