name: Make Release Tag
on: 
  push:
    branches:
    - prod
    
jobs:
    release-on-push:
      permissions:
        contents: write
        pull-requests: read
      runs-on: ubuntu-latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      steps:
        - uses: rymndhng/release-on-push-action@master
          with:
            bump_version_scheme: minor