name: Publish Package to npmjs
on:
  release:
    types: [published, created]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.RELEASE_KEY }}
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm install -g yarn
      - run: yarn install --frozen-lockfile
      - run: yarn workspace mini-md publish --provenance
        env:
          VERSON: ${{ github.event.release.tag_name }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          